#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rest
Version  : 0.8.0
Release  : 1
URL      : http://ftp.gnome.org/pub/GNOME/sources/rest/0.8/rest-0.8.0.tar.xz
Source0  : http://ftp.gnome.org/pub/GNOME/sources/rest/0.8/rest-0.8.0.tar.xz
Summary  : RESTful web api query library
Group    : Development/Tools
License  : LGPL-2.1
Requires: rest-lib
Requires: rest-data
Requires: rest-doc
BuildRequires : ca-certs
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsoup-gnome-2.4)
BuildRequires : pkgconfig(libxml-2.0)

%description
librest
=======
This library has been designed to make it easier to access web services that
claim to be "RESTful". A reasonable definition of what this means can be found
on Wikipedia [1]. However a reasonable description is that a RESTful service
should have urls that represent remote objects which methods can then be
called on.

%package data
Summary: data components for the rest package.
Group: Data

%description data
data components for the rest package.


%package dev
Summary: dev components for the rest package.
Group: Development
Requires: rest-lib
Requires: rest-data
Provides: rest-devel

%description dev
dev components for the rest package.


%package doc
Summary: doc components for the rest package.
Group: Documentation

%description doc
doc components for the rest package.


%package lib
Summary: lib components for the rest package.
Group: Libraries
Requires: rest-data

%description lib
lib components for the rest package.


%prep
%setup -q -n rest-0.8.0

%build
export LANG=C
%configure --disable-static --with-ca-certificates=/usr/share/ca-certs/
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gir-1.0/Rest-0.7.gir
/usr/share/gir-1.0/RestExtras-0.7.gir

%files dev
%defattr(-,root,root,-)
/usr/include/rest-0.7/rest-extras/flickr-proxy-call.h
/usr/include/rest-0.7/rest-extras/flickr-proxy.h
/usr/include/rest-0.7/rest-extras/lastfm-proxy-call.h
/usr/include/rest-0.7/rest-extras/lastfm-proxy.h
/usr/include/rest-0.7/rest-extras/youtube-proxy.h
/usr/include/rest-0.7/rest/oauth-proxy-call.h
/usr/include/rest-0.7/rest/oauth-proxy.h
/usr/include/rest-0.7/rest/oauth2-proxy-call.h
/usr/include/rest-0.7/rest/oauth2-proxy.h
/usr/include/rest-0.7/rest/rest-enum-types.h
/usr/include/rest-0.7/rest/rest-param.h
/usr/include/rest-0.7/rest/rest-params.h
/usr/include/rest-0.7/rest/rest-proxy-auth.h
/usr/include/rest-0.7/rest/rest-proxy-call.h
/usr/include/rest-0.7/rest/rest-proxy.h
/usr/include/rest-0.7/rest/rest-xml-node.h
/usr/include/rest-0.7/rest/rest-xml-parser.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/Rest-0.7.typelib
/usr/lib64/girepository-1.0/RestExtras-0.7.typelib
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/rest-0.7/FlickrProxy.html
/usr/share/gtk-doc/html/rest-0.7/FlickrProxyCall.html
/usr/share/gtk-doc/html/rest-0.7/LastfmProxy.html
/usr/share/gtk-doc/html/rest-0.7/LastfmProxyCall.html
/usr/share/gtk-doc/html/rest-0.7/OAuth2Proxy.html
/usr/share/gtk-doc/html/rest-0.7/OAuth2ProxyCall.html
/usr/share/gtk-doc/html/rest-0.7/OAuthProxy.html
/usr/share/gtk-doc/html/rest-0.7/OAuthProxyCall.html
/usr/share/gtk-doc/html/rest-0.7/RestProxy.html
/usr/share/gtk-doc/html/rest-0.7/RestProxyCall.html
/usr/share/gtk-doc/html/rest-0.7/RestXmlParser.html
/usr/share/gtk-doc/html/rest-0.7/ch01.html
/usr/share/gtk-doc/html/rest-0.7/ch02.html
/usr/share/gtk-doc/html/rest-0.7/ch03.html
/usr/share/gtk-doc/html/rest-0.7/ch04.html
/usr/share/gtk-doc/html/rest-0.7/ch05.html
/usr/share/gtk-doc/html/rest-0.7/home.png
/usr/share/gtk-doc/html/rest-0.7/index.html
/usr/share/gtk-doc/html/rest-0.7/index.sgml
/usr/share/gtk-doc/html/rest-0.7/ix01.html
/usr/share/gtk-doc/html/rest-0.7/ix02.html
/usr/share/gtk-doc/html/rest-0.7/left-insensitive.png
/usr/share/gtk-doc/html/rest-0.7/left.png
/usr/share/gtk-doc/html/rest-0.7/rest-0.7.devhelp2
/usr/share/gtk-doc/html/rest-0.7/rest-RestParam.html
/usr/share/gtk-doc/html/rest-0.7/rest-RestParams.html
/usr/share/gtk-doc/html/rest-0.7/right-insensitive.png
/usr/share/gtk-doc/html/rest-0.7/right.png
/usr/share/gtk-doc/html/rest-0.7/style.css
/usr/share/gtk-doc/html/rest-0.7/up-insensitive.png
/usr/share/gtk-doc/html/rest-0.7/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
